// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationClient interface {
	// NotifyStream is a bidirectional stream for offset notifications.
	// Each peer opens one stream; both sides send OffsetNotify messages.
	NotifyStream(ctx context.Context, opts ...grpc.CallOption) (Replication_NotifyStreamClient, error)
	// Fetch retrieves effect bytes by offset from the origin node.
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) NotifyStream(ctx context.Context, opts ...grpc.CallOption) (Replication_NotifyStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Replication_serviceDesc.Streams[0], "/swytch.cluster.v1.Replication/NotifyStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationNotifyStreamClient{stream}
	return x, nil
}

type Replication_NotifyStreamClient interface {
	Send(*OffsetNotify) error
	Recv() (*OffsetNotify, error)
	grpc.ClientStream
}

type replicationNotifyStreamClient struct {
	grpc.ClientStream
}

func (x *replicationNotifyStreamClient) Send(m *OffsetNotify) error {
	return x.ClientStream.SendMsg(m)
}

func (x *replicationNotifyStreamClient) Recv() (*OffsetNotify, error) {
	m := new(OffsetNotify)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *replicationClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, "/swytch.cluster.v1.Replication/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServer is the server API for Replication service.
// All implementations must embed UnimplementedReplicationServer
// for forward compatibility
type ReplicationServer interface {
	// NotifyStream is a bidirectional stream for offset notifications.
	// Each peer opens one stream; both sides send OffsetNotify messages.
	NotifyStream(Replication_NotifyStreamServer) error
	// Fetch retrieves effect bytes by offset from the origin node.
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	mustEmbedUnimplementedReplicationServer()
}

// UnimplementedReplicationServer must be embedded to have forward compatible implementations.
type UnimplementedReplicationServer struct {
}

func (UnimplementedReplicationServer) NotifyStream(Replication_NotifyStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method NotifyStream not implemented")
}
func (UnimplementedReplicationServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedReplicationServer) mustEmbedUnimplementedReplicationServer() {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s *grpc.Server, srv ReplicationServer) {
	s.RegisterService(&_Replication_serviceDesc, srv)
}

func _Replication_NotifyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).NotifyStream(&replicationNotifyStreamServer{stream})
}

type Replication_NotifyStreamServer interface {
	Send(*OffsetNotify) error
	Recv() (*OffsetNotify, error)
	grpc.ServerStream
}

type replicationNotifyStreamServer struct {
	grpc.ServerStream
}

func (x *replicationNotifyStreamServer) Send(m *OffsetNotify) error {
	return x.ServerStream.SendMsg(m)
}

func (x *replicationNotifyStreamServer) Recv() (*OffsetNotify, error) {
	m := new(OffsetNotify)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Replication_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swytch.cluster.v1.Replication/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Replication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "swytch.cluster.v1.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Replication_Fetch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NotifyStream",
			Handler:       _Replication_NotifyStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cluster/proto/replication.proto",
}
